//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Clinica.WsClinica {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_SERVERSoap", Namespace="http://tempuri.org/")]
    public partial class WS_SERVER : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Registrar_UsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Remover_UsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Login_UsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Doctor_Data_CitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Registrar_DoctorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Remover_DoctorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Login_DoctorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agendar_CitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Remover_CitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_Cita_DOCTOROperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_Cita_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_DOCTORESOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_SERVER() {
            this.Url = global::Clinica.Properties.Settings.Default.Clinica_WsClinica_WS_SERVER;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Registrar_UsuarioCompletedEventHandler Registrar_UsuarioCompleted;
        
        /// <remarks/>
        public event Remover_UsuarioCompletedEventHandler Remover_UsuarioCompleted;
        
        /// <remarks/>
        public event Login_UsuarioCompletedEventHandler Login_UsuarioCompleted;
        
        /// <remarks/>
        public event Data_UserCompletedEventHandler Data_UserCompleted;
        
        /// <remarks/>
        public event Doctor_Data_CitaCompletedEventHandler Doctor_Data_CitaCompleted;
        
        /// <remarks/>
        public event Registrar_DoctorCompletedEventHandler Registrar_DoctorCompleted;
        
        /// <remarks/>
        public event Remover_DoctorCompletedEventHandler Remover_DoctorCompleted;
        
        /// <remarks/>
        public event Login_DoctorCompletedEventHandler Login_DoctorCompleted;
        
        /// <remarks/>
        public event Agendar_CitaCompletedEventHandler Agendar_CitaCompleted;
        
        /// <remarks/>
        public event Remover_CitaCompletedEventHandler Remover_CitaCompleted;
        
        /// <remarks/>
        public event Data_Cita_DOCTORCompletedEventHandler Data_Cita_DOCTORCompleted;
        
        /// <remarks/>
        public event Data_Cita_UserCompletedEventHandler Data_Cita_UserCompleted;
        
        /// <remarks/>
        public event Data_DOCTORESCompletedEventHandler Data_DOCTORESCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Registrar_Usuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Registrar_Usuario(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string telefono) {
            object[] results = this.Invoke("Registrar_Usuario", new object[] {
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        correo,
                        password,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Registrar_UsuarioAsync(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string telefono) {
            this.Registrar_UsuarioAsync(cedula, nombre, apellido1, apellido2, correo, password, telefono, null);
        }
        
        /// <remarks/>
        public void Registrar_UsuarioAsync(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string telefono, object userState) {
            if ((this.Registrar_UsuarioOperationCompleted == null)) {
                this.Registrar_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrar_UsuarioOperationCompleted);
            }
            this.InvokeAsync("Registrar_Usuario", new object[] {
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        correo,
                        password,
                        telefono}, this.Registrar_UsuarioOperationCompleted, userState);
        }
        
        private void OnRegistrar_UsuarioOperationCompleted(object arg) {
            if ((this.Registrar_UsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Registrar_UsuarioCompleted(this, new Registrar_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remover_Usuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Remover_Usuario(string cedula) {
            object[] results = this.Invoke("Remover_Usuario", new object[] {
                        cedula});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Remover_UsuarioAsync(string cedula) {
            this.Remover_UsuarioAsync(cedula, null);
        }
        
        /// <remarks/>
        public void Remover_UsuarioAsync(string cedula, object userState) {
            if ((this.Remover_UsuarioOperationCompleted == null)) {
                this.Remover_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemover_UsuarioOperationCompleted);
            }
            this.InvokeAsync("Remover_Usuario", new object[] {
                        cedula}, this.Remover_UsuarioOperationCompleted, userState);
        }
        
        private void OnRemover_UsuarioOperationCompleted(object arg) {
            if ((this.Remover_UsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Remover_UsuarioCompleted(this, new Remover_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login_Usuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login_Usuario(string cedula, string pass) {
            object[] results = this.Invoke("Login_Usuario", new object[] {
                        cedula,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Login_UsuarioAsync(string cedula, string pass) {
            this.Login_UsuarioAsync(cedula, pass, null);
        }
        
        /// <remarks/>
        public void Login_UsuarioAsync(string cedula, string pass, object userState) {
            if ((this.Login_UsuarioOperationCompleted == null)) {
                this.Login_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogin_UsuarioOperationCompleted);
            }
            this.InvokeAsync("Login_Usuario", new object[] {
                        cedula,
                        pass}, this.Login_UsuarioOperationCompleted, userState);
        }
        
        private void OnLogin_UsuarioOperationCompleted(object arg) {
            if ((this.Login_UsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Login_UsuarioCompleted(this, new Login_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_User(string cedula) {
            object[] results = this.Invoke("Data_User", new object[] {
                        cedula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_UserAsync(string cedula) {
            this.Data_UserAsync(cedula, null);
        }
        
        /// <remarks/>
        public void Data_UserAsync(string cedula, object userState) {
            if ((this.Data_UserOperationCompleted == null)) {
                this.Data_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_UserOperationCompleted);
            }
            this.InvokeAsync("Data_User", new object[] {
                        cedula}, this.Data_UserOperationCompleted, userState);
        }
        
        private void OnData_UserOperationCompleted(object arg) {
            if ((this.Data_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_UserCompleted(this, new Data_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Doctor_Data_Cita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Doctor_Data_Cita(string cedula) {
            object[] results = this.Invoke("Doctor_Data_Cita", new object[] {
                        cedula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Doctor_Data_CitaAsync(string cedula) {
            this.Doctor_Data_CitaAsync(cedula, null);
        }
        
        /// <remarks/>
        public void Doctor_Data_CitaAsync(string cedula, object userState) {
            if ((this.Doctor_Data_CitaOperationCompleted == null)) {
                this.Doctor_Data_CitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoctor_Data_CitaOperationCompleted);
            }
            this.InvokeAsync("Doctor_Data_Cita", new object[] {
                        cedula}, this.Doctor_Data_CitaOperationCompleted, userState);
        }
        
        private void OnDoctor_Data_CitaOperationCompleted(object arg) {
            if ((this.Doctor_Data_CitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Doctor_Data_CitaCompleted(this, new Doctor_Data_CitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Registrar_Doctor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Registrar_Doctor(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string especialidad, string telefono) {
            object[] results = this.Invoke("Registrar_Doctor", new object[] {
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        correo,
                        password,
                        especialidad,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Registrar_DoctorAsync(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string especialidad, string telefono) {
            this.Registrar_DoctorAsync(cedula, nombre, apellido1, apellido2, correo, password, especialidad, telefono, null);
        }
        
        /// <remarks/>
        public void Registrar_DoctorAsync(string cedula, string nombre, string apellido1, string apellido2, string correo, string password, string especialidad, string telefono, object userState) {
            if ((this.Registrar_DoctorOperationCompleted == null)) {
                this.Registrar_DoctorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrar_DoctorOperationCompleted);
            }
            this.InvokeAsync("Registrar_Doctor", new object[] {
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        correo,
                        password,
                        especialidad,
                        telefono}, this.Registrar_DoctorOperationCompleted, userState);
        }
        
        private void OnRegistrar_DoctorOperationCompleted(object arg) {
            if ((this.Registrar_DoctorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Registrar_DoctorCompleted(this, new Registrar_DoctorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remover_Doctor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Remover_Doctor(string cedula) {
            object[] results = this.Invoke("Remover_Doctor", new object[] {
                        cedula});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Remover_DoctorAsync(string cedula) {
            this.Remover_DoctorAsync(cedula, null);
        }
        
        /// <remarks/>
        public void Remover_DoctorAsync(string cedula, object userState) {
            if ((this.Remover_DoctorOperationCompleted == null)) {
                this.Remover_DoctorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemover_DoctorOperationCompleted);
            }
            this.InvokeAsync("Remover_Doctor", new object[] {
                        cedula}, this.Remover_DoctorOperationCompleted, userState);
        }
        
        private void OnRemover_DoctorOperationCompleted(object arg) {
            if ((this.Remover_DoctorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Remover_DoctorCompleted(this, new Remover_DoctorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login_Doctor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login_Doctor(string cedula, string pass) {
            object[] results = this.Invoke("Login_Doctor", new object[] {
                        cedula,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Login_DoctorAsync(string cedula, string pass) {
            this.Login_DoctorAsync(cedula, pass, null);
        }
        
        /// <remarks/>
        public void Login_DoctorAsync(string cedula, string pass, object userState) {
            if ((this.Login_DoctorOperationCompleted == null)) {
                this.Login_DoctorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogin_DoctorOperationCompleted);
            }
            this.InvokeAsync("Login_Doctor", new object[] {
                        cedula,
                        pass}, this.Login_DoctorOperationCompleted, userState);
        }
        
        private void OnLogin_DoctorOperationCompleted(object arg) {
            if ((this.Login_DoctorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Login_DoctorCompleted(this, new Login_DoctorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agendar_Cita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agendar_Cita(string cedula_cliente, string cedula_doctor, string fecha_hora, string detalle) {
            object[] results = this.Invoke("Agendar_Cita", new object[] {
                        cedula_cliente,
                        cedula_doctor,
                        fecha_hora,
                        detalle});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agendar_CitaAsync(string cedula_cliente, string cedula_doctor, string fecha_hora, string detalle) {
            this.Agendar_CitaAsync(cedula_cliente, cedula_doctor, fecha_hora, detalle, null);
        }
        
        /// <remarks/>
        public void Agendar_CitaAsync(string cedula_cliente, string cedula_doctor, string fecha_hora, string detalle, object userState) {
            if ((this.Agendar_CitaOperationCompleted == null)) {
                this.Agendar_CitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgendar_CitaOperationCompleted);
            }
            this.InvokeAsync("Agendar_Cita", new object[] {
                        cedula_cliente,
                        cedula_doctor,
                        fecha_hora,
                        detalle}, this.Agendar_CitaOperationCompleted, userState);
        }
        
        private void OnAgendar_CitaOperationCompleted(object arg) {
            if ((this.Agendar_CitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agendar_CitaCompleted(this, new Agendar_CitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remover_Cita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Remover_Cita(string ID_Cita, string cedula_doc, string fecha) {
            object[] results = this.Invoke("Remover_Cita", new object[] {
                        ID_Cita,
                        cedula_doc,
                        fecha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Remover_CitaAsync(string ID_Cita, string cedula_doc, string fecha) {
            this.Remover_CitaAsync(ID_Cita, cedula_doc, fecha, null);
        }
        
        /// <remarks/>
        public void Remover_CitaAsync(string ID_Cita, string cedula_doc, string fecha, object userState) {
            if ((this.Remover_CitaOperationCompleted == null)) {
                this.Remover_CitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemover_CitaOperationCompleted);
            }
            this.InvokeAsync("Remover_Cita", new object[] {
                        ID_Cita,
                        cedula_doc,
                        fecha}, this.Remover_CitaOperationCompleted, userState);
        }
        
        private void OnRemover_CitaOperationCompleted(object arg) {
            if ((this.Remover_CitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Remover_CitaCompleted(this, new Remover_CitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_Cita_DOCTOR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_Cita_DOCTOR(string doc_cedula) {
            object[] results = this.Invoke("Data_Cita_DOCTOR", new object[] {
                        doc_cedula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_Cita_DOCTORAsync(string doc_cedula) {
            this.Data_Cita_DOCTORAsync(doc_cedula, null);
        }
        
        /// <remarks/>
        public void Data_Cita_DOCTORAsync(string doc_cedula, object userState) {
            if ((this.Data_Cita_DOCTOROperationCompleted == null)) {
                this.Data_Cita_DOCTOROperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_Cita_DOCTOROperationCompleted);
            }
            this.InvokeAsync("Data_Cita_DOCTOR", new object[] {
                        doc_cedula}, this.Data_Cita_DOCTOROperationCompleted, userState);
        }
        
        private void OnData_Cita_DOCTOROperationCompleted(object arg) {
            if ((this.Data_Cita_DOCTORCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_Cita_DOCTORCompleted(this, new Data_Cita_DOCTORCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_Cita_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_Cita_User(string user_cedula) {
            object[] results = this.Invoke("Data_Cita_User", new object[] {
                        user_cedula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_Cita_UserAsync(string user_cedula) {
            this.Data_Cita_UserAsync(user_cedula, null);
        }
        
        /// <remarks/>
        public void Data_Cita_UserAsync(string user_cedula, object userState) {
            if ((this.Data_Cita_UserOperationCompleted == null)) {
                this.Data_Cita_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_Cita_UserOperationCompleted);
            }
            this.InvokeAsync("Data_Cita_User", new object[] {
                        user_cedula}, this.Data_Cita_UserOperationCompleted, userState);
        }
        
        private void OnData_Cita_UserOperationCompleted(object arg) {
            if ((this.Data_Cita_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_Cita_UserCompleted(this, new Data_Cita_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_DOCTORES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_DOCTORES() {
            object[] results = this.Invoke("Data_DOCTORES", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_DOCTORESAsync() {
            this.Data_DOCTORESAsync(null);
        }
        
        /// <remarks/>
        public void Data_DOCTORESAsync(object userState) {
            if ((this.Data_DOCTORESOperationCompleted == null)) {
                this.Data_DOCTORESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_DOCTORESOperationCompleted);
            }
            this.InvokeAsync("Data_DOCTORES", new object[0], this.Data_DOCTORESOperationCompleted, userState);
        }
        
        private void OnData_DOCTORESOperationCompleted(object arg) {
            if ((this.Data_DOCTORESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_DOCTORESCompleted(this, new Data_DOCTORESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Registrar_UsuarioCompletedEventHandler(object sender, Registrar_UsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Registrar_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Registrar_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Remover_UsuarioCompletedEventHandler(object sender, Remover_UsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Remover_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Remover_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Login_UsuarioCompletedEventHandler(object sender, Login_UsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Login_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Login_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Data_UserCompletedEventHandler(object sender, Data_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Doctor_Data_CitaCompletedEventHandler(object sender, Doctor_Data_CitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Doctor_Data_CitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Doctor_Data_CitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Registrar_DoctorCompletedEventHandler(object sender, Registrar_DoctorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Registrar_DoctorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Registrar_DoctorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Remover_DoctorCompletedEventHandler(object sender, Remover_DoctorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Remover_DoctorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Remover_DoctorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Login_DoctorCompletedEventHandler(object sender, Login_DoctorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Login_DoctorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Login_DoctorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Agendar_CitaCompletedEventHandler(object sender, Agendar_CitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agendar_CitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agendar_CitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Remover_CitaCompletedEventHandler(object sender, Remover_CitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Remover_CitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Remover_CitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Data_Cita_DOCTORCompletedEventHandler(object sender, Data_Cita_DOCTORCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_Cita_DOCTORCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_Cita_DOCTORCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Data_Cita_UserCompletedEventHandler(object sender, Data_Cita_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_Cita_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_Cita_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Data_DOCTORESCompletedEventHandler(object sender, Data_DOCTORESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_DOCTORESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_DOCTORESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591